language: python

python:
     - "3.6.3"

install:
  - pip install -r requirements.txt

script:
  # - pytest 
  - coverage report
  - coverage run -m pytest
  - coverage xml
  
  

after_success:
  - coveralls