language: python

python:
     - "3.6.3"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install overalls

script:
  - pytest -v --cov tests --cov-report term-missing
  - coverage xml
  - coverage report

after_success:
  - coveralls